/**
  초기 설정
 */
DROP DATABASE IF EXISTS BASEMENT;
CREATE DATABASE BASEMENT;
USE BASEMENT;
DROP TABLE IF EXISTS MEMBER;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRODUCT_IMAGE_FILE;

/**
  멤버 테이블
 */
CREATE TABLE MEMBER (
    MEMBER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,   /* 멤버 기본키 Sequence */
    MEMBER_EMAIL VARCHAR(50) NOT NULL,  /* 멤버 이메일 */
    MEMBER_PWD VARCHAR(50) NOT NULL,  /* 멤버 비밀번호 */
    MEMBER_NAME VARCHAR(20) NOT NULL, /* 멤버 이름 */
    MEMBER_PHONE VARCHAR(20) NOT NULL,  /* 멤버 전화번호 */
    MEMBER_NICKNAME VARCHAR(20) NOT NULL, /* 멤버 닉네임 */
    MEMBER_EMAIL_CHECK VARCHAR(1) NOT NULL, /* 멤버 이메일 수신여부 동의  Y or N */
    MEMBER_ROLE VARCHAR(10) NOT NULL,
    MEMBER_GRADE VARCHAR(10) NOT NULL,  /* 멤버 등급 BRONZE, SILVER, GOLD */
    MEMBER_REG_DATE DATETIME NOT NULL,  /* 멤버 등록날짜 */
    MEMBER_UPDATE_DATE DATETIME NOT NULL  /* 멤버 업데이트 날짜 */
);

/**
  카테고리 테이블
 */
CREATE TABLE CATEGORY (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, /* 카테고리 기본키 Sequence */
    CATEGORY_NAME VARCHAR(50) NOT NULL  /* 카테고리 이름 */
);

/**
  상품 테이블
 */
CREATE TABLE PRODUCT (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  /* 상품 기본키 Sequence */
    PRODUCT_NAME VARCHAR(30) NOT NULL, /* 상품 이름 */
    PRODUCT_PRICE INT NOT NULL, /* 상품 가격 */
    PRODUCT_STOCK INT NOT NULL, /* 상품 재고 */
    PRODUCT_DESC VARCHAR(4000) NOT NULL, /* 상품 설명 */
    PRODUCT_HITS INT, /* 상품 조회수 */
    PRODUCT_REG_DATE DATETIME NOT NULL, /* 상품 등록날자 */
    PRODUCT_UPDATE_DATE DATETIME NOT NULL /* 상품 업데이트 날짜 */
);

/**
  상품 이미지 테이블
 */
CREATE TABLE PRODUCT_IMAGE_FILE (
    FILE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  /* 상품 이미지 파일 기본키 Sequence */
    ORIGIN_FILE_NAME VARCHAR(300) NOT NULL, /* 이미지 원본 파일 이름 */
    STORED_FILE_NAME VARCHAR(300) NOT NULL, /* 이미지 저장 파일 이름 */
    DELEGATE_THUMNAIL VARCHAR(1) NOT NULL,  /* 썸네일 여부 Y or N */
    FILE_SIZE INT NOT NULL, /* 이미지 사이즈 */
    FILE_DELETE_CHECK VARCHAR(1) NOT NULL,  /* 파일 삭제 여부 Y or N */
    FILE_REG_DATE DATETIME NOT NULL, /* 이미지 등록 날짜 */
    FILE_UPDATE_DATE DATETIME NOT NULL /* 이미지 수정 날짜 */
);

/**
  외래키 설정
 */
ALTER TABLE PRODUCT ADD CATEGORY_ID INT;
ALTER TABLE PRODUCT
ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

ALTER TABLE PRODUCT_IMAGE_FILE ADD PRODUCT_ID INT;
ALTER TABLE PRODUCT_IMAGE_FILE
ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);