CREATE TABLE MEMBER (

    MEMBER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,   /* 멤버 기본키 Sequence */
    MEMBER_EMAIL VARCHAR(50) NOT NULL,  /* 멤버 이메일 */
    MEMBER_PWD VARCHAR(50) NOT NULL,  /* 멤버 비밀번호 */
    MEMBER_NAME VARCHAR(20) NOT NULL, /* 멤버 이름 */
    MEMBER_PHONE VARCHAR(20) NOT NULL,  /* 멤버 전화번호 */
    MEMBER_NICKNAME VARCHAR(20) NOT NULL, /* 멤버 닉네임 */
    MEMBER_EMAIL_CHECK VARCHAR(1) NOT NULL, /* 멤버 이메일 수신여부 동의  Y or N */
    MEMBER_GRADE VARCHAR(10) NOT NULL,  /* 멤버 등급 BRONZE, SILVER, GOLD */
    MEMBER_REG_DATE DATETIME NOT NULL,  /* 멤버 등록날짜 */
    MEMBER_UPDATE_DATE DATETIME NOT NULL  /* 멤버 업데이트 날짜 */
)
